package enums;

public enum USER {
    SELLER(true, 0, "seller_urban@mailsac.com","VHt*zzt*wQNu6XS","Mpho", "Etam", "Mbebe",  "", "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzYyODQ0MDksImV4cCI6MTcwNzM4ODQwOSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9TRUxMRVIiXSwiZW1haWwiOiJzZWxsZXJfdXJiYW5AbWFpbHNhYy5jb20iLCJpZCI6MTQ4NCwiZmlyc3ROYW1lIjoiTXBobyIsInBpY3R1cmUiOm51bGwsImdvb2dsZUlkIjpudWxsLCJmYWNlYm9va0lkIjpudWxsLCJsaW5rZWRpbklkIjpudWxsLCJnaXRodWJJZCI6bnVsbCwiYXBwbGVJZCI6bnVsbCwiaXNWZXJpZmllZCI6ZmFsc2UsInBob25lIjpudWxsLCJkZXZpY2VUb2tlbiI6IjAiLCJjcmVhdGVkIjp7ImRhdGUiOiIyMDIzLTAxLTE3IDE0OjIxOjI1LjAwMDAwMCIsInRpbWV6b25lX3R5cGUiOjMsInRpbWV6b25lIjoiVVRDIn0sInBheXBhbEFjY291bnRJZCI6bnVsbCwibGF0Ijo1NS44NjQyMzcsImxuZyI6LTQuMjUxODA2LCJicm93c2VyTm90aWZpY2F0aW9ucyI6ZmFsc2UsImFsbG93QW5vbnltb3VzQ2hhdCI6dHJ1ZSwiemlwQ29kZSI6bnVsbCwiZGVsaXZlcnlUeXBlIjpbIkJVWUVSX1BJQ0tVUF9GUk9NX0JSQU5DSCJdLCJtYXhEZWxpdmVyeVJhbmdlIjowLCJmcmVlRGVsaXZlcnlSYW5nZSI6MCwibWluRnJlZURlbGl2ZXJ5T3JkZXIiOjAsInBlck1pbGVDb3N0IjowLCJhdmFpbGFiaWxpdHkiOiIiLCJlc3RpbWF0ZWREZWxpdmVyeVRpbWUiOltdLCJhdmFpbGFiaWxpdHlCcmFuY2giOiIwODowMC0xNzowMCIsIm1pZGRsZU5hbWUiOiJFdGFtIiwibGFzdE5hbWUiOiJNYmViZSIsImZsZXhpYmxlRGVsaXZlcnlPcHRpb25zIjpbXX0.FA2QJrbnY-mX8C6Du3a9npN-ETvnaAz4fW8dnrZZqd5c7yBS7d5iC35JzoIRgkwKpuhwX7wtv0wKn-KpAIfXAkibyk2BcQxuKXscVgxWN-OfD98gkYty53nAuTBl7u2Wu0ZBQWyr0wjuQLCFr4xsQkJmK08UvzhO81YY1l6Mca130EfNVHjHdIpoP-SjITBAFqafq7zKECiE2hvhU_UjqP-leg94aOFAByUqyqN3U-hNQAkStLDA-A3kZJER86Vh9uYAIu3T68aVFu0ZJuQdYywaRR0ellYhPnjLatbX3AlvSGXeFW1OpW8VTvtzvH0j4F_ory2RBMeVxaa17_02xQ"),
    BUYER(true, 0,"buyer_urban@mailsac.com","VHt*zzt*wQNu6XS","Cristian", "Ronaldo", "Santos",   "", "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzY3MjQzMjYsImV4cCI6MTcwNzgyODMyNiwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9TRUxMRVIiXSwiZW1haWwiOiJidXllcl91cmJhbkBtYWlsc2FjLmNvbSIsImlkIjoxNDg1LCJmaXJzdE5hbWUiOiJDcmlzdGlhbiIsInBpY3R1cmUiOiIvdXBsb2Fkcy91c2VyLzE0ODUvNjNlNWMwNjQ4YjViMy5wbmciLCJnb29nbGVJZCI6bnVsbCwiZmFjZWJvb2tJZCI6bnVsbCwibGlua2VkaW5JZCI6bnVsbCwiZ2l0aHViSWQiOm51bGwsImFwcGxlSWQiOm51bGwsImlzVmVyaWZpZWQiOmZhbHNlLCJwaG9uZSI6IisxICg1NzUpIDAzOC01MDcwIiwiZGV2aWNlVG9rZW4iOiIwIiwiY3JlYXRlZCI6eyJkYXRlIjoiMjAyMy0wMS0xNyAxNDoyMzo1MS4wMDAwMDAiLCJ0aW1lem9uZV90eXBlIjozLCJ0aW1lem9uZSI6IlVUQyJ9LCJwYXlwYWxBY2NvdW50SWQiOm51bGwsImxhdCI6NTQuOTc0NDE4NSwibG5nIjotMS42NTgzNDk4LCJicm93c2VyTm90aWZpY2F0aW9ucyI6ZmFsc2UsImFsbG93QW5vbnltb3VzQ2hhdCI6dHJ1ZSwiemlwQ29kZSI6bnVsbCwiZGVsaXZlcnlUeXBlIjpbIkJVWUVSX1BJQ0tVUF9GUk9NX0JSQU5DSCIsIlNFTExFUl9GTEVYSUJMRSJdLCJtYXhEZWxpdmVyeVJhbmdlIjowLCJmcmVlRGVsaXZlcnlSYW5nZSI6NywibWluRnJlZURlbGl2ZXJ5T3JkZXIiOjIzMCwicGVyTWlsZUNvc3QiOjIsImF2YWlsYWJpbGl0eSI6IiIsImVzdGltYXRlZERlbGl2ZXJ5VGltZSI6WyI2MF8yIl0sImF2YWlsYWJpbGl0eUJyYW5jaCI6IjA4OjAwLTE3OjAwIiwibWlkZGxlTmFtZSI6IlJvbmFsZG8iLCJsYXN0TmFtZSI6IlNhbnRvcyIsImZsZXhpYmxlRGVsaXZlcnlPcHRpb25zIjpbeyJpZCI6MTE0OCwiZGVsaXZlcnlCeSI6MTY4NCwib3JkZXJCZWdpbiI6MTY4Mywib3JkZXJFbmQiOjE2ODR9XX0.BKjEWUUZU5b6p5elkMarWR9V742LzD93mrAoaXcln84Z2Zn_O762_93QKkf3FzPbmQLK8_dz34f7GkqzxlnAtaWCw92mzmqi_ktmvid0489NH1-5FqD54WQYBjJ1sY1S0AslKB9XQnHdb1ta69dPsDbnDUfYCspVAOXSwwlFAi-lfIY8YXAlPbja5EYdXDV2D7xTBiYWzPGt76YVTRzhVta1c07vbvot-ZfcBMqFwfgXRhIBZ6Q2Vk5mChd_zAThXnRRI-c9Q5Oi9EmHxGrlNDlq56LESiOGxGJ8rh-jXUENZ95A2b6ZT3-7n2L2HJ_8IY5jOZ8VNyr7iKOKfmzIQQ"),
    BUYER2(true, "buyer_urban@mailsac.com","VHt*zzt*wQNu6XS",""),
    BUYER3(true,"urbanicfarm2@yopmail.com","Urbanicfarm2/","eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzgyNDc2NjcsImV4cCI6MTcwOTM1MTY2Nywicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9TRUxMRVIiXSwiZW1haWwiOiJ1cmJhbmljZmFybTJAeW9wbWFpbC5jb20iLCJpZCI6MTc3NCwiZmlyc3ROYW1lIjoiQmlsZ2UiLCJwaWN0dXJlIjpudWxsLCJnb29nbGVJZCI6bnVsbCwiZmFjZWJvb2tJZCI6bnVsbCwibGlua2VkaW5JZCI6bnVsbCwiZ2l0aHViSWQiOm51bGwsImFwcGxlSWQiOm51bGwsImlzVmVyaWZpZWQiOmZhbHNlLCJwaG9uZSI6bnVsbCwiZGV2aWNlVG9rZW4iOiIwIiwiY3JlYXRlZCI6eyJkYXRlIjoiMjAyMy0wMi0yNCAyMDo0Mjo1MC4wMDAwMDAiLCJ0aW1lem9uZV90eXBlIjozLCJ0aW1lem9uZSI6IlVUQyJ9LCJwYXlwYWxBY2NvdW50SWQiOm51bGwsImxhdCI6NTQuOTc0MzAxNiwibG5nIjotMS42NTc2NjIsImJyb3dzZXJOb3RpZmljYXRpb25zIjpmYWxzZSwiYWxsb3dBbm9ueW1vdXNDaGF0Ijp0cnVlLCJ6aXBDb2RlIjpudWxsLCJkZWxpdmVyeVR5cGUiOlsiQlVZRVJfUElDS1VQX0ZST01fQlJBTkNIIiwiQlVZRVJfUElDS1VQIl0sIm1heERlbGl2ZXJ5UmFuZ2UiOjMsImZyZWVEZWxpdmVyeVJhbmdlIjozLCJtaW5GcmVlRGVsaXZlcnlPcmRlciI6MywicGVyTWlsZUNvc3QiOjMsImF2YWlsYWJpbGl0eSI6IjEwOjQwLTEyOjQwIiwiZXN0aW1hdGVkRGVsaXZlcnlUaW1lIjpbIjYwXzMiXSwiYXZhaWxhYmlsaXR5QnJhbmNoIjoiMDM6MDAtMDQ6MDAiLCJtaWRkbGVOYW1lIjoiIiwibGFzdE5hbWUiOiJNYWhpciIsImZsZXhpYmxlRGVsaXZlcnlPcHRpb25zIjpbXX0.Z9lOpedmUSZHa737yMrJPXoc_RZSb-5wqQCeKc2AeVUDnEPKs2LoikT9QjHJLcdYL60_4Gl9yVyB27e9nYgoHQMoFabCbfdIvNPOGUgpStzC2TKQad-lLggku4qmOdISqqeOZsCvz0g07r1UlukxKmt_Or2UZobdPem9T7sU5ApO-cpW2p_apvU-8mbRqQ3TduoKIXvqP0xmdeCC0mQHnnTn4xpvSqF3p18qBI-ni0dHnBqQKnYcFPOLuGt75j77iB338bhF9c9T0Ja-OgXRs2n-RY8qRzfGJg8GD9B3LeEOfy_rTDu5TmDm65TIGYme_A_tnbf8bLaRU4GmoEQ5TQ"),

    EZRA(true, 0, "ezra_test@mailsac.com","Farmer*21", "", "", "", "", "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2Nzc4Njk0ODUsImV4cCI6MTcwODk3MzQ4NSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9TRUxMRVIiXSwiZW1haWwiOiJlenJhX3Rlc3RAbWFpbHNhYy5jb20iLCJpZCI6MTY0MiwiZmlyc3ROYW1lIjoiRXpyYSIsInBpY3R1cmUiOm51bGwsImdvb2dsZUlkIjpudWxsLCJmYWNlYm9va0lkIjpudWxsLCJsaW5rZWRpbklkIjpudWxsLCJnaXRodWJJZCI6bnVsbCwiYXBwbGVJZCI6bnVsbCwiaXNWZXJpZmllZCI6ZmFsc2UsInBob25lIjoibnVsbCIsImRldmljZVRva2VuIjoiMCIsImNyZWF0ZWQiOnsiZGF0ZSI6IjIwMjMtMDEtMjkgMjA6MjY6MzguMDAwMDAwIiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJVVEMifSwicGF5cGFsQWNjb3VudElkIjpudWxsLCJsYXQiOjQzLjY0MjU2NTcsImxuZyI6LTc5LjM4NzA1NTcsImJyb3dzZXJOb3RpZmljYXRpb25zIjpmYWxzZSwiYWxsb3dBbm9ueW1vdXNDaGF0Ijp0cnVlLCJ6aXBDb2RlIjoiNzc3NzciLCJkZWxpdmVyeVR5cGUiOlsiQlVZRVJfUElDS1VQX0ZST01fQlJBTkNIIiwiU0VMTEVSX0RFTElWRVJZIl0sIm1heERlbGl2ZXJ5UmFuZ2UiOjUsImZyZWVEZWxpdmVyeVJhbmdlIjo1LCJtaW5GcmVlRGVsaXZlcnlPcmRlciI6NSwicGVyTWlsZUNvc3QiOjUsImF2YWlsYWJpbGl0eSI6IiIsImVzdGltYXRlZERlbGl2ZXJ5VGltZSI6WyIxODBfNiJdLCJhdmFpbGFiaWxpdHlCcmFuY2giOiIwODowMC0xNzowMCIsIm1pZGRsZU5hbWUiOiJudWxsIiwibGFzdE5hbWUiOiJBcGF5ZGluIiwiZmxleGlibGVEZWxpdmVyeU9wdGlvbnMiOltdfQ.rfS9A7ETuiFkCtEqJB3y2lxHrlLnraRlU_GP838f2LW2pY4UmEY-hvyQvDQrmHVVnNkEhQ7joCfZKDOiQOP0pgu7NXEIMxfgWxG40H6gtqk-y3OLQwVqfTtB8kf8EelqOSaOOzoNPon82xzPRNJ3zelB3CBEa5dPk4Xocze_D_BjROEotZW8m3utWyX0Yz3z7dXupdZYTjg600Ia8Oe9FQWprgxMZgTgy9dr-pxt7WmMFUOHJ-I7EFJUx-ZOyfv4Oa3zpw6o0BuPqABx3ppqbPZQJxl1Erk_XEt4B3zR48qyOkvTzq4k-yNXwCRiI3j4zKNw4JDZ-jzKMhKxc3KTsA"),
    SELLER1(true, 0, "seller_urban2@yopmail.com","Seller2/", "", "", "", "","eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzgxMjM5NjIsImV4cCI6MTcwOTIyNzk2Miwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9TRUxMRVIiXSwiZW1haWwiOiJzZWxsZXJfdXJiYW4yQHlvcG1haWwuY29tIiwiaWQiOjE3NzMsImZpcnN0TmFtZSI6IkRlbml6IiwicGljdHVyZSI6bnVsbCwiZ29vZ2xlSWQiOm51bGwsImZhY2Vib29rSWQiOm51bGwsImxpbmtlZGluSWQiOm51bGwsImdpdGh1YklkIjpudWxsLCJhcHBsZUlkIjpudWxsLCJpc1ZlcmlmaWVkIjpmYWxzZSwicGhvbmUiOm51bGwsImRldmljZVRva2VuIjoiMCIsImNyZWF0ZWQiOnsiZGF0ZSI6IjIwMjMtMDItMjQgMjA6Mzg6MTYuMDAwMDAwIiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJVVEMifSwicGF5cGFsQWNjb3VudElkIjpudWxsLCJsYXQiOjUxLjUyMTg3NDgsImxuZyI6LTAuMTEzMDYxNywiYnJvd3Nlck5vdGlmaWNhdGlvbnMiOmZhbHNlLCJhbGxvd0Fub255bW91c0NoYXQiOnRydWUsInppcENvZGUiOm51bGwsImRlbGl2ZXJ5VHlwZSI6WyJCVVlFUl9QSUNLVVBfRlJPTV9CUkFOQ0giXSwibWF4RGVsaXZlcnlSYW5nZSI6MCwiZnJlZURlbGl2ZXJ5UmFuZ2UiOjAsIm1pbkZyZWVEZWxpdmVyeU9yZGVyIjowLCJwZXJNaWxlQ29zdCI6MCwiYXZhaWxhYmlsaXR5IjoiIiwiZXN0aW1hdGVkRGVsaXZlcnlUaW1lIjpbXSwiYXZhaWxhYmlsaXR5QnJhbmNoIjoiMDg6MDAtMTc6MDAiLCJtaWRkbGVOYW1lIjoiIiwibGFzdE5hbWUiOiJaZW5naW4iLCJmbGV4aWJsZURlbGl2ZXJ5T3B0aW9ucyI6W119.Do6oExNqS6YpzWTRoPgye-rD1CtMMd5eBaEioDmdw66I6TsEYsGpSwhcga1hNQYR01B-fYTD6rMhYYdfyCv38hY6fScH4PgDLaV0T-sh0JrBFA9orgriNEBhtI0ep1jtPiyhi4tddMM1zmR0ukAaOdNEVaM-fRRd6mmnr7BGOGwIUED-SwpjkaXA2Kg3Q2Tshxb0ihCqcRziV2ZDujhnx4u9fpuzQdu0H07Q6Xd0-tk9bXIiW25yx8ZtbZfWYHTvAs6Xif2DAnWypkIGI_8Hv2qmuUXSN62pMAa1ICeqPTDi_Fs2YYt0jj8cG_7j4wD8b25HRDhEnc9c6mLeGgV3VA"),;

    ;

    private boolean isTest;
    private int userId;
    private String token, firstName, middleName, lastName, password, email, postalCode;

    USER(boolean isTest, int userId, String email, String password, String firstName, String middleName, String lastName, String postalCode, String token) {
        this.isTest = isTest;
        this.userId = userId;
        this.token = token;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.password = password;
        this.email = email;
        this.postalCode = postalCode;
    }

    USER(boolean isTest, String email, String password ,String postalCode ) {
        this.isTest = isTest;
        this.userId = userId;
        this.token = token;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.password = password;
        this.email = email;
        this.postalCode = postalCode;
    }

    public boolean isTest() {
        return isTest;
    }

    public int getUserId() {
        return userId;
    }

    public String getToken() {
        return token;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getMiddleName() {
        return middleName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getPassword() {
        return password;
    }

    public String getEmail() {
        return email;
    }

    public String getPostalCode() {
        return postalCode;
    }
}
